# Build customization
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
release:
  github:
    owner: uw-labs
    name: strongbox
archive:
  files:
  - none*
