# Build customization
builds:
  - ldflags: -s -extldflags "-static" -X "main.version=git-tag:`{{.Env.CIRCLE_TAG}}`, git-sha1=`{{.Env.CIRCLE_SHA1}}`"
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
release:
  github:
    owner: uw-labs
    name: strongbox
archive:
  wrap_in_directory: true
