# Site settings
baseurl = "http://uw-labs.github.io/strongbox"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Strongbox - Encryption for git users."
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "your_google_analytics_code"
hasCJKLanguage = true
publishDir = "../"
[params]
	name = "Strongbox"
	description = "Strongbox - Encryption for git users."
	bio = ""
	# Enter optionally your twitter account
	twitter = ""
	enableRSS = false

	# Disqus comment
	disqusShortname = ""
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	# Duoshuo comment
	duoshuoShortname = ""
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = true

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
  github-square = "https://github.com/uw-labs"
